CHANGELOG.md, lib/store_model/types/array_type.rb, spec/store_model/types/array_type_spec.rb
An attempt to resolve this issue: #32 
The simple solution is to use ArrayType as wrapper around its @model_klass and delegate type casting to it
I just made a quick look and fix, I'm not sure is there any caveats 🤔
=> Fix :unknown_attributes assignment for ArrayType

docs/unknown_attributes.md
Describe correct way to initialize store model instance with wrong attributes
___________________
```Ruby
Configuration.new(color: "red", archived: true)
```
Usage `new` calls constructor from `ActiveModel::Model` which simply assigns attributes and we end up with `ActiveModel::UnknownAttributeError`
In this case first we need to build type and then call `cast_value`
=> Update unknown_attributes doc

CHANGELOG.md, lib/store_model/model.rb, lib/store_model/version.rb, spec/dummy/app/models/configuration.rb, spec/store_model/model_spec.rb, spec/store_model/types/json_type_spec.rb
This change ensures that falsey values are reflected correctly when printing
out the final result - they currently print out as `nil`. For example:
```ruby
class MyStoreModel < StoreModel
attribute :one, :integer, default: 1
attribute :two, :boolean, default: false
attribute :three, :string, default: nil
end
```
Current Behavior: `<MyStoreModel one: 1, two: nil, three: nil>`
Expected Behavior:  `<MyStoreModel one: 1, two: false, three: nil>`
=> Fix inspect output for falsey values

store_model.gemspec
Hey @DmitryTsepelev, thanks for making a great library. It was pretty much exactly what I was looking for :)
I added it to my Rails app but noticed it depends on all of rails, and not just active record. My app doesn't use all of Rails (most of it, but not Active Storage), and I don't want that dependency if I can avoid it.
Is this change ok?
=> Depend on activerecord only in the gemspec

docs/enums.md, docs/unknown_attributes.md, docs/validations.md
Thank you for creating this great gem! I noticed a few syntax errors in documentation. Please review my pull request. Thanks!
=> Fix syntax errors in code blocks in documentation

CHANGELOG.md, lib/active_model/validations/store_model_validator.rb, spec/active_model/validations/store_model_validator_spec.rb
The previous implementation used `any?` to validate ArrayType. That has the effect elements after the first invalid element don't get validated and their errors collection isn't populated.
This fix makes sure to call `invalid?` on every element of the array before setting an error on the parent record.
=> Validate all elements of ArrayType

CHANGELOG.md, lib/active_model/validations/store_model_validator.rb, lib/store_model.rb, lib/store_model/type_builders.rb, lib/store_model/types.rb, lib/store_model/types/array_type.rb, lib/store_model/types/base_array_type.rb, lib/store_model/types/base_single_type.rb, lib/store_model/types/json_type.rb, lib/store_model/types/one_of.rb, lib/store_model/types/polymorphic_array_type.rb, lib/store_model/types/polymorphic_helper.rb, lib/store_model/types/polymorphic_type.rb, spec/active_model/validations/store_model_validator_spec.rb, spec/store_model/types/polymorphic_array_type_spec.rb, spec/store_model/types/polymorphic_type_spec.rb
=> Add polymorfic associations

lib/store_model/model.rb, spec/dummy/app/models/configuration.rb, spec/store_model/model_spec.rb
Change `StoreModel::Model#has_attribute?` to respond `true` on aliased attributes.
The same changes were made on Rails 6.1 : 
* https://github.com/rails/rails/blob/6-1-stable/activerecord/lib/active_record/attribute_methods.rb#L170-L189
* https://github.com/rails/rails/commit/c53c418e6f1ac5297bdec9851b87f3a345be069d
=> Handle aliases with has_attributes

CHANGELOG.md, lib/store_model/model.rb, spec/dummy/app/models/bicycle.rb, spec/store_model/model_spec.rb
This PR adds predicate methods as suggested in #89. 
It is loosely modeled after the [implementation in rails](https://github.com/rails/rails/blob/56d8ff83726bb6c0b1f570deb057835f90a75e30/activerecord/lib/active_record/attribute_methods/query.rb). 
I'm not 100% sure about the `method_missing` based implementation but at least that is how rails does it. Any thoughts?
=> Add predicate methods (#89)

CHANGELOG.md, lib/store_model/model.rb, spec/store_model/model_spec.rb
This PR introduces `#hash` method for StoreModel::Model instance based on attributes hash.
This going to unlock using rspec matchers for example:
```ruby
expect { subject }.not_to change { settings.reload.configuration }
```
=> Add hash method

lib/store_model.rb
Using store_model without rails was also discussed in #71. Trying to
load the railtie would raise an error in that case.
=> Don't load railtie if there is no rails

docs/enums.md, lib/store_model/enum.rb, spec/store_model/enum_spec.rb
Adds support for `_prefix` and `_suffix` options to enum types, similar to `ActiveRecord::Enum`
=> Add support for enum affixes

lib/store_model/model.rb, spec/dummy/db/schema.rb, spec/store_model/types/one_spec.rb
Got a wake up call last night while I was debugging an issue. I got the realization that I needed to access a value in one of my store model which I had not defined as an attribute. When I fetched it from the db and tried to access unknown_attributes I noticed it was not persisted :(
Then I saw #72 and noticed that it was a known issue :) 
Just creating this PR although the implementation is already completed by you guys @andresespinosapc @DmitryTsepelev 
I really have no claim in knowing what the hell I'm doing regarding rspec and test structure in general but felt like the least I could do is a basic attempt in order to get the discussion going. seeing as the other PR is more than a year old.
I really think this feature is a great addition.
Please feel free to take over the …
=> brute force basic test to check if unknown_attributes are persisted after save.

lib/store_model/model.rb, spec/store_model/cast_validation_spec.rb
For attributes that have a cast type provided the validation was performed using the cast value and not the raw value. This is problematic in the case of a float attribute that can be greater than or equal to 0. 
```
attribute :amount, :float
validates :amount, numericality: { greater_than_or_equal_to: 0 }
```
When a bad value is passed to the float attribute i.e "junk" it is cast to 0.0 which passes the numericality check. 
Including the [ActiveRecord::AttributeMethods::BeforeTypeCast](https://api.rubyonrails.org/classes/ActiveRecord/AttributeMethods/BeforeTypeCast.html) module allows the raw value to be validated. 
[numericality](https://github.com/rails/rails/blob/7-0-stable/activemodel/lib/active_model/validations/numericality.rb#L123-L142) accessing the raw …
=> Fix validation for cast attributes

.github/workflows/rspec.yml
An unquoted 3.0 is truncated to a 3, leading to the latest Ruby 3 version being loaded.  At this time that's a Ruby 3.1.x version, which is not what's intended.
Quoting the 3.0 ensures that a 3.0.x version is loaded for these lines in CI.
=> Quote 3.0 in the CI configuration

lib/store_model/model.rb, spec/store_model/model_spec.rb
Similar to what [ActiveRecord does](https://github.com/rails/rails/blob/04972d9b9ef60796dc8f0917817b5392d61fcf09/activerecord/lib/active_record/core.rb#L586), add an alias to the `:==` method for `:eql?`. This allows a `StoreModel` to be used as a hash key or in set operations. 
Note that we use `alias` here and not `alias_method` since this is defined in a module. Also, all of the related specs are extracted into a shared example that is used for all comparison methods.
=> Alias `:==` as `:eql?`

docs/unknown_attributes.md, lib/store_model/configuration.rb, lib/store_model/model.rb, lib/store_model/types/many_base.rb, lib/store_model/types/one.rb, lib/store_model/types/one_polymorphic.rb, spec/store_model/model_spec.rb, spec/store_model/types/many_spec.rb, spec/store_model/types/one_polymorphic_spec.rb
Follow up PR for the discussion in #108.
This PR adds the possibility to configure if unknown attributes get serialized when `as_json` is called on a  `StoreModel::Model` instance.
e.g. to turn of serialization of unknown attributes globally one could set
```ruby
StoreModel.config.serialize_unknown_attributes = false
```
by default this settings is set to `true` to not break the existing behavior.
=> Add config option `serialize_unknown_attributes`

lib/store_model/model.rb, spec/store_model/model_spec.rb
Motivated by [ActiveModel::AttributeSet](https://github.com/rails/rails/blob/c3675f50d2e59b7fc173d7b332860c4b1a24a726/activemodel/lib/active_model/attribute_set.rb#L14-L20), I suggest adding access to attributes using brackets.
When we are using `ActiveRecordModel` and [serialized attributes](https://api.rubyonrails.org/classes/ActiveRecord/AttributeMethods/Serialization/ClassMethods.html#method-i-serialize), we have access to the nested attributes using brackets.
=> Add access to attributes using brackets

.rubocop.yml, lib/store_model/model.rb, spec/dummy/app/models/configuration.rb, spec/dummy/app/models/method_model.rb, spec/store_model/model_spec.rb
When relying on delegation of `fetch` to `attributes` there are some issues that can cause unexpected / mis-matched behavior due to the underlying keys in the `attributes` hash.
For example, when we have an object that looks like the following, we'll get different behavior due to `fetch`'s exception handling.
```ruby
class Configuration
attribute :id
end
example = Configuration.new
puts example.id # nil
puts example.fetch(:id) # KeyError: key not found: :id
```
See https://github.com/DmitryTsepelev/store_model/commit/d8c468e817b951d20ba82fdff22a53747357d6f4 which shows the passing behavior, and https://github.com/DmitryTsepelev/store_model/commit/b651dbbc5689c8df72dc37d4773b153a19a1e7f2 which shows the failing behavior.
We discovered this in our usage of a gem …
=> 🐛  Fix `fetch` to handle `nil` values

lib/store_model/nested_attributes.rb, spec/store_model/nested_attributes_spec.rb
Similar to the `accepts_nested_attributes_for` active record, the idea here is to support the `allow_destroy` option in the `accepts_nested_attributes_for` store_model method.
For example:
`accepts_nested_attributes_for [:suppliers, allow_destroy: true]`
Active Record documentation: https://api.rubyonrails.org/classes/ActiveRecord/NestedAttributes/ClassMethods.html#method-i-accepts_nested_attributes_for
=> Support option "allow_destroy" to accepts_nested_attributes_for

lib/store_model/nested_attributes.rb, lib/store_model/types/many_base.rb, lib/store_model/types/one_base.rb, spec/store_model/nested_attributes_spec.rb
This is an improvement for [this PR](https://github.com/DmitryTsepelev/store_model/pull/138).
The idea here is to automatically adds `_destroy` attribute in the association class when `allow_destroy` is true.
```ruby
class Requirement
attribute :categories, Category.to_array_type
accepts_nested_attributes_for [:categories, { allow_destroy: true }]
end
```
```ruby
class Category
attr_accessor :_destroy
end
```
```ruby
class Category
end
```
=> fix: Add _destroy attr_accessor for association in nested attributes

docs/enums.md, lib/store_model/enum.rb, spec/store_model/enum_spec.rb
Hi there! I hope it was all right to open this PR directly. I'm a first-time contributor so go easy on me and let me know how you'd like me to contribute this, if it's welcome.
Take a class with an enum defined:
```ruby
class Configuration
enum :status, {off: 0, on: 1}
end
```
Currently, it's only possible to access the enum mapping on instances:
```ruby
Configuration.new.status_values # => {:off=>0, :on=>1}
```
But the mapping is defined on the class, so there's no reason this shouldn't also work, which is how it also works in ActiveRecord:
```ruby
Configuration.status_values # => {:off=>0, :on=>1}
```
This PR defines that method on the class.
In Rails, it's also possible to access the enum mapping via the pluralized enum name, e.g.
```ruby …
```
=> Create class enum accessor

CHANGELOG.md, docs/enums.md, lib/store_model/enum.rb, spec/store_model/enum_spec.rb
As @BoberMod pointed out in https://github.com/DmitryTsepelev/store_model/pull/135#discussion_r1124487764, that PR introduces a regression in cases where the name of an enum is already pluralized; specifically, the instance method to access the enum _value_ is superseded with the instance method to access the enum _mapping_.
Since there's already a _class_ method to access the enum mapping, and the precedent (in ActiveRecord) doesn't set an instance method to access the enum mapping anyway, this PR removes the instance method to access the enum mapping.
I hope the diff in `docs/enums.md` and the specs sufficiently illustrate the practical difference!
=> Remove enum mapping instance method

docs/unknown_attributes.md
We didn't pass `serialize_unknown_attributes` option in the sample code that explains the behavior when the option is passed.
=> docs: fix missing option in sample code

CHANGELOG.md, docs/enums.md, lib/store_model/configuration.rb, lib/store_model/model.rb, spec/dummy/app/models/configuration.rb, spec/spec_helper.rb, spec/store_model/model_spec.rb, spec/store_model/types/one_polymorphic_spec.rb, spec/store_model/types/one_spec.rb
Fixes #151. Turn on the config option `StoreModel.config.serialize_enums_using_as_json = true`
=> Model#as_json serializes key-value enums using keys

README.md, lib/store_model/nested_attributes.rb, spec/dummy/app/models/store.rb, spec/dummy/db/schema.rb, spec/store_model/nested_attributes_spec.rb
This makes it possible to use the complete Rails pathway for nested form objects.
Also updates `accepts_nested_attributes_for` to allow the Rails-syntax.
```ruby
class Supplier < ActiveRecord::Base
include StoreModel::NestedAttributes
has_many :bicycles, dependent: :destroy
attribute :products, Product.to_array_type
accepts_nested_attributes_for :bicycles, :products, allow_destroy: true
end
```
This will allow the form builders to work their magic:
```erb
<%= form_with model: @supplier do |form| %>
<%= form.fields_for :products do |product_fields| %>
<%= product_fields.text_field :name %>
<% end %>
<% end %>
```
Resulting in:
```html
<input type="text" name="supplier[products_attributes][0][name]" id="supplier_products_attributes_0_name">
```
In the controller:
```ruby
def create …
```
=> Use accepts_nested_attributes_for with StoreModel::NestedAttributes

lib/store_model/model.rb, lib/store_model/types.rb, lib/store_model/types/one.rb, lib/store_model/types/raw_json.rb, spec/dummy/app/models/anything.rb, spec/dummy/db/schema.rb, spec/store_model/model_spec.rb, spec/store_model/nested_attributes_spec.rb, spec/store_model/types/many_polymorphic_spec.rb, spec/store_model/types/many_spec.rb, spec/store_model/types/one_polymorphic_spec.rb
Fixes #150, which tracks a breaking change in serialization and persistence of json object.
After `v1.6.2`, nested models received multiple serialization passes. This broke all json queries against the persisted rows. I merged in the test which @trumanshuck used to isolate the version, then added a fix from there.
This PR removes `values_for_database` and patches `as_json` so nested `Hash` and `StoreModel` attributes will only serialized as JSON once. For array attributes, it delegates to `as_json`, so they are safe as well.
This ensures:
- the entire object and all nested attributes are query-able through your database's particular json syntax
- all nested attribute's `Type` will be used for serialization/deserialization, so things like timestamps and encryption work.
=> Fix serialization on nested objects

lib/store_model/nested_attributes.rb, spec/store_model/nested_attributes_spec.rb
Override of accepts_nested_attributes_for was calling for attribute_types method which is taking attribute types from schema if your model is active-record, which will not work when you do not yet have db prepared or your new model is not yet created in database but you already declared everything in your model's class. In some cases it was preventing of 'rails db:create' and 'rails db:migrate'
Override of assign_nested_attributes_for_collection_association was accepting more arguments than it's super method declared in active record, which was breaking one_to_many relations with accept_nested_attributes_for this relation.
Also, plain rails do not support per relation declaration of options for accepts_nested_attributes_for (https://api.rubyonrails.org/classes/ActiveRecord/NestedAttributes …
=> Override of accepts_nested_attributes_for breaks app start when connection to db is not available

lib/store_model/types/one.rb, spec/store_model/types/one_spec.rb
=> fixes #160 - addresses error deserializing malformed json string

lib/store_model/model.rb, spec/store_model/model_spec.rb
While debugging code backed by `StoreModel`, I had issues understanding some model attributes, as those that were more complex objects just printed the attribute's class and its memory address.
I saw something like:
```
=> #<Content::Text type: text, text: #<Content::Text::Base:0x000000011a9716f0>>
```
By contrast, the default Ruby `inspect` implementation calls `inspect` on all the object's instance variables:
```
=> #<OuterClass:0x0000000104ac87f8 @attribute=#<InnerClass:0x000000010466cf60 @text="string">>
```
Also, the strings are not quoted, making strings like `"nil"` and `"false"` show up as `nil` and `false`, which may lead to confusion.
This commit changes the `inspect` implementation to call `inspect` on the model attributes, fixing the issues stated above.
=> Improve `inspect` readability

docs/enums.md, lib/store_model/enum.rb, lib/store_model/types/enum_type.rb, spec/store_model/enum_spec.rb, spec/store_model/types/enum_type_spec.rb
Hey, just recently I was working on an API where I had to add a validation on enum attributes. Unfortunately, there were no other validation mechanisms before passing the parameters to the model. Therefore, the `store_model` instance raised an error every time a wrong value was passed to the API.
I checked the `ActiveRecord::Enum` behavior and found, that they have a `validate: boolean` parameter, that turns off the raising an exception and adds a validation for the field to the model. I'm not sure if we should interfere with the model, so here is my implementation of the enum that supports a new parameter `raise_on_invalid_values: boolean (default: true)` just so we turn off the check.
Not sure if it's a good idea to update the type, or maybe it would be better to create another type …
=> Manageable raising on invalid enum value

docs/unknown_attributes.md
While validating updates to the StoreModel, I encountered a change in behavior concerning the handling of unknown attributes during database storage operations. Specifically, I noticed that starting from version 2.1.1, the `serialize_unknown_attributes` option, when set to `false`, prevents unknown attributes from being stored in the database. Hence, I've updated the documentation.
=> Update documentation to reflect behavior of `serialize_unknown_attributes` in v2.1.1+

.github/workflows/rspec.yml, README.md, docs/enable_parent_assignment.md, lib/store_model/configuration.rb, lib/store_model/railtie.rb, spec/dummy/config/initializers/enable_parent_assignment.rb, spec/spec_helper.rb, spec/store_model/configuration_spec.rb, spec/store_model/model_spec.rb
* Optional parent tracking functionality. Can be disabled with settings.
* Docs updated.
* Specs changed to verify both approaches, including github actions workflow.
```
expect("Verify correct github workflow").to eq("This should fail too see ENV ENABLE_PARENT_ASSIGNMENT working")
```
Fixes #167
=> Optional parent tracking

docs/unknown_attributes.md, lib/store_model/types/one.rb, spec/store_model/types/many_polymorphic_spec.rb, spec/store_model/types/many_spec.rb, spec/store_model/types/one_polymorphic_spec.rb, spec/store_model/types/one_spec.rb
Our application uses StoreModel with the `serialize_unknown_attributes` option set to `false`.
Previously, StoreModel versions prior to 2.1.1 always stored unknown attributes in the database. However, now, unknown attributes are not stored unless the `serialize_unknown_attributes` option is set to `true`. This change was inconvenient for us; therefore, we want to restore the behavior of storing unknown attributes in the database, regardless of the setting of the `serialize_unknown_attributes` option.
The fix was straightforward. Furthermore, to ensure this behavior does not break, I have improved the tests for the `serialize` method in each `Type` class.
However, this change will again alter the behavior of storing unknown attributes in the database. I considered adding an option to …
=> Restore behavior to always store unknown attributes in the database

docs/enums.md
In reading the doc additions for [PR 164](https://github.com/DmitryTsepelev/store_model/pull/164/files#diff-14ac46a6a99731e4b04cb07dfce19f325ecbb4d65c2a42f00b7af1abfdeb2ed7R77) (Manageable raising on invalid enum value) the example would throw an ArgumentError with 
```
`enum': wrong number of arguments (given 0, expected 1..2) (ArgumentError)
```
This was due to how `enum` was being called in the example. This PR updates the docs the reflect the right method arguments.
=> Update enums.md docs to reflect enum argument order when `raise_on_invalid_values` is set

lib/store_model/model.rb, lib/store_model/types/many_base.rb, lib/store_model/types/one.rb, lib/store_model/types/one_polymorphic.rb, spec/spec_helper.rb, spec/store_model/nested_attributes_spec.rb, spec/store_model/types/many_polymorphic_spec.rb, spec/store_model/types/many_spec.rb, spec/store_model/types/one_polymorphic_spec.rb, spec/store_model/types/one_spec.rb
In the current latest version 2.4.0, I noticed that serialization options are not applied to nested objects. For example, when specifying the `serialize_enums_using_as_json` option in the `as_json` method, it behaves as follows:
```ruby
StoreModel.config.serialize_enums_using_as_json = false
class Message
attribute :child, to_type
enum :status, in: { unread: 0, read: 1 }
end
message = Message.new(status: "read", child: { status: "unread" })
message.as_json(
serialize_enums_using_as_json: true
) # => { "child" => { "child" => nil, "status" => 0 }, "status" => "read" }
```
The same issue occurs with the `serialize_unknown_attributes` option.
This problem seems to arise because the `as_json` method serializes nested objects recursively; however, the serialization …
=> Fix issue with serialization options not applied to nested objects

lib/store_model/model.rb, spec/store_model/nested_attributes_spec.rb
After the introduction of #171, I found an issue with my nested model containing an array with no elements in it (due to `default: []`).
This PR first checks if the array is empty, before validating if all values are `StoreModel::Model` objects.
=> Fixed issue for empty nested array

lib/store_model/types/many_base.rb, spec/store_model/types/many_spec.rb
Fixes https://github.com/DmitryTsepelev/store_model/issues/174
Root cause:
```ruby
[].all? # => true
[].any? # => false
[ StoreModel::Model.allocate ].all? { |v| v.is_a?(StoreModel::Model) # => true
```
So, to check if all are StoreModel::Model, we need to
1. (new) check the array has something in it
2. check that everything in it is a StoreModel::Model
=> fix: serialize empty has-many array

lib/store_model/types/one.rb, lib/store_model/types/one_polymorphic.rb, spec/store_model/model_spec.rb, spec/store_model/types/one_polymorphic_spec.rb, spec/store_model/types/one_spec.rb
issue #120 - first try an easy way
=> Treat all Hash-like input as a Hash

.github/workflows/rspec.yml, .github/workflows/rubocop.yml, .rubocop.yml, CHANGELOG.md, Gemfile, gemfiles/jruby.gemfile, gemfiles/rails_7_1.gemfile, gemfiles/rails_7_2.gemfile, lib/store_model/model.rb, lib/store_model/nested_attributes.rb, lib/store_model/types/enum_type.rb, lib/store_model/types/many.rb, lib/store_model/types/many_polymorphic.rb, lib/store_model/types/one.rb, lib/store_model/types/one_polymorphic.rb, spec/dummy/app/models/configuration.rb, spec/dummy/db/schema.rb, spec/store_model/nested_attributes_spec.rb, store_model.gemspec
=>  Update Ruby and Rails versions, raise an error when database is not available

lib/store_model/types/enum_type.rb, spec/store_model/types/enum_type_spec.rb
When creating enums that contains enum value type float, it throws errors of invalid type. This PR fixes the issue.
I am having a scenario where I need my enum to be defined as { key => float } mapping.
This is my class
```
class Inputs
attribute :in_temp, :float, default: 29
attribute :ext_temp, :float, default: 50
attribute :rel_humid, :float, default: 70
attribute :ins_thick, :float, default: 10
enum :surf_emis, in: {
high_surface: '10.0',
medium_surface: '8.0',
low_surface: '5.7'
}, default: :medium_surface
validates :in_temp, :ext_temp, :rel_humid, :surf_emis, :ins_thick, presence: true
end
```
Now the issue is,
It only works if keys value pair is { key => integer }, but for integer I can not handle value `5.7`
I tried using string but it also throws error. …
=> Fixed issues with enum that contains type float

docs/nested_models.md
As requested in https://github.com/DmitryTsepelev/store_model/issues/187#issuecomment-2453483373, this PR adds an explanation and known workaround for the `accepts_nested_attributes_for` Rails 7.2+ issue.
=> Update nested_models.md with workaround notes as per #187

README.md, docs/instantiation.md, lib/store_model/model.rb, spec/store_model/model_spec.rb
Closes #191 
Adds convenience methods `StoreModel::Model.from_value` and `StoreModel::Model.from_values` to instantiate `StoreModel::Model` classes from a type, rather than from the class itself, thus getting type behaviors like unknown attribute handling.
=> Add convenience methods to instantiate model from type

lib/store_model/nested_attributes.rb, lib/store_model/types.rb, lib/store_model/types/base.rb, lib/store_model/types/many_base.rb, lib/store_model/types/one_base.rb, spec/store_model/nested_attributes_spec.rb
manually store types of attributes defined by storemodel and use it for nested attributes preprocessing when db connection of activerecord model is not available.
add single types/base to simplify storemodel attribute detection.
=> fix `accepts_nested_attributes_for` triggering db connection in rails 7.2

lib/store_model/nested_attributes.rb, spec/store_model/nested_attributes_spec.rb
=> Fix for AR association accepts_nested_attributes_for and a raise_if proc

docs/unions.md, lib/store_model.rb, lib/store_model/model.rb, spec/dummy/db/schema.rb, spec/store_model/discriminator_attribute_spec.rb, spec/store_model/union_spec.rb
This PR implements #210 (in a slightly different way)
`StoreModel.union([Dog, Cat, Reptile]).to_type` to get a type that can hold one of `Dog`, `Cat` or `Reptile` by an discriminator attribute `"type"`.
Add `discriminator_attribute value: "dog"` to set up the discriminator on the `StoreModel::Model`s.
The discriminator key is configurable in both places, as is the value of the attribute.
=> Union types: Convenience layer over OneOf
